### PR TITLE
Fixup clippy lints

### PR DESCRIPTION
**Pull request by Hoverbear**
Fallout from #52

### CODE REVIEW

**Comment by CreepySkeleton** [comment]
I would actually recommend you to set clippy as "allow failure" or something.

**Comment by Hoverbear** [comment]
Thanks for your recommendation, but that's not how this project rolls. :)

**Comment by CreepySkeleton** [comment]
Hard mode on :) Admirable and a little bit crazy

**Comment by Hoverbear** [comment]
Yeah -- I'm actually really miffed about the Ci issue on #47/#48, those are the first broken codes to land in getset :(

**Comment by CreepySkeleton** [comment]
image

**Comment by Hoverbear** [comment]
Oh it was totally my fault, don't you feel sad little kitty! I'm grateful for your efforts. :)

**Pull request merged**
