### PR TITLE
Must use

### LINKED ISSUE #40: Generate #[must_use] for getters
Getters don't make sense if their values are unused, and most likely implies a forgotten bug or a misunderstanding of the API.

I am not sure whether marking a function `#[must_use]` breaks semver BC, but it would be healthy to add more `#[must_use]`.

### PR DESCRIPTION
**Pull request by Hoverbear**
Fixes #40 .

I'd love to hear more opinions on this! cc @djc @Boscop

### CODE REVIEW

**Comment by djc** [comment]
I'm... unconvinced. As far as I know `must_use` is mostly used for things like `Result` or `Future` where not using the value with a large probability constitutes a logical error, and so it is not usually applied to all the getters. Here, instead (as far as I can tell from a quick review), it results merely in an unused value -- so not sure this adds that much value.

**Comment by Hoverbear** [comment]
This is good feedback! I'm pretty lukewarm about the idea. While having a getter go unused is ~probably~ a bug, I'm not sure it's in scope here.

**Comment by SOF3** [comment]
I don't see any reason why a getter would be unused though.

**Comment by Razican** [comment]
If someone wants to lint for unused results (that don't have the `#[must_use]` attribute, they can lint on `unused_results`, so I think this should only be added for stuff that would probably break logic, as @djc suggested. Maybe it could be an optional attribute to the getters, but I don't think it's worth it to add it to all getters.

**Comment by Hoverbear** [comment]
Let's close it then.

**Pull request closed without merging**
