### PR TITLE
Return primitive types by value from getters

### PR DESCRIPTION
**Pull request by Dushistov**

### CODE REVIEW

**Comment by Dushistov** [comment]
@Boscop 

Yes, it doesn't handle type aliases, also `struct Generic<T> {  #[get] x: T }` not handled.
But I suppose this cases are not part this PR.
It minimize code writing for obvious case `struct Foo { #[get] x: i32 }`,
other cases require syntax's invention (like you suggest `#[get = "*"]`)
and may be discussion and I hope would be handled by different PR.

**Comment by Boscop** [comment]
I agree that it would be nice to have both: use copying by default for primitives, **and** still have the special syntax to be able to also use it for type aliases and non-primitive `Copy` types.

Btw, why are you using a `HashSet`+macro instead of a match statement to keep the code simple? :)

**Comment by Boscop** [comment]
@Dushistov Yes, I agree with you, one way to reduce the amount of typing for `#[get = "pub"] #[set = "pub"]` is to automatically imply `get` when writing `set` (and to imply both when writing `get_mut`), I proposed this here: https://github.com/Hoverbear/getset/issues/4

**Comment by SOF3** [comment]
Selectively having certain Copy types dereferenced and some not looks really confusing and inconsistent. Is it so hard to do a `*` on the return value?

**Comment by Hoverbear** [comment]
I think #29 is a simpler solution to this without any magic. What do you think?

**Comment by Hoverbear** [comment]
Closing this. :) Feel free to reopen if you'd prefer.

**Pull request closed without merging**
